config/routes.rb
FirstApp::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do

    get 'signin',  to: 'devise/sessions#new'
    get 'signout', to: 'devise/sessions#destroy'
    get 'signup',  to: 'devise/registrations#new'
  end

  namespace :admin do
    resources :hotels, only: [:index, :edit, :update] do
      collection do
        post :import
      end
    end

    get 'database' => "database#index"

    root to: 'welcome#index'
  end

  resources :authentications
  resources :hotels do
    member do
      get :connecters
      post :upload

      get :send_user, action: 'send_user_form'
      put :send_user
    end
  end

  resources :microposts do
    member do
      get :send_msg, action: 'send_msg_form'
      put :send_msg
    end
  end  

  resources :users do
    member {get :following, :followers}
    member {get :connecting}
  end

  resources :prices do
    member {get :historical}
  end

  resources :permlinks, only: [:show]

  resources :relationships, only: [:create, :destroy]
  resources :prices, only: [:create, :destroy]
  resources :connections, only: [:create, :destroy]
 
  match '/staticcontact', to: 'static_pages#staticcontact'
  get '/cities/:city_code', to: 'static_pages#by_city'
  get '/countries/:country_code', to: 'static_pages#by_country'
  get '/companies/:company_code', to: 'static_pages#by_company'

  root to: 'static_pages#index'

end

app/views/shared/_body_button.html.erb
<div class="thumbnail" style="height: 400px">
  <table class="table table-condensed">  
  <% owners = Hotel.uniq.pluck(:owner) %>
  <% owners.reject! { |c| c.nil? } %>
  <% owners.reject! { |c| c.empty? } %>
  <% owners.in_groups_of(2,false).each do |owner_row|  %>
    <tr class="active">
      <% owner_row.each do |owner| %>
      <% owner_name = owner.gsub(' ', '-') %>
      <td><%= link_to owner, "/companies/"+owner_name, class:"btn btn-link" %></td>
          <% end %>
    </tr>
  <% end %>
  </table>
</div>

<div class="carousel-caption">
</div>

app/views/shared/_body_google.html.erb
<div class="thumbnail" style="height: 400px">
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{request.location.latitude}%2C#{request.location.longitude}" %>
</div>
<div class="carousel-caption">
</div>

app/views/shared/_body_picture.html.erb
<div class="thumbnail" style="height: 400px">
  <%= image_tag("http://placehold.it/200x400") %>
</div>
<div class="carousel-caption">
</div>

app/views/shared/_message_main.html.erb
<div class="row">
  <div class="col-md-12">
    <%= text_area_tag :message, nil, placeholder: "Message", rows:"2" %>  
  </div>
</div>

app/views/shared/_subject_loggedin.html.erb
<div class="row">
  <div class="col-md-12">  
    <%= text_field_tag :subject, nil, placeholder: "Subject"%>
  </div>
</div>

app/views/shared/_subject_main.html.erb
<div class="row">
  <div class="col-md-12">  
    <%= text_field_tag :subject, nil, placeholder: "Subject"%>
  </div>
</div>

app/views/shared/_summary_price.html.erb
<% price = Price.for_date_and_hotel(firstDate, summary_price).first %>

<td>
  <% unless (price.id rescue nil).nil? || (price.rate rescue nil).nil? %>
    <%= link_to number_to_currency(price.rate), historical_price_path(price.id) %>
  <% else %>
    <%= number_to_currency(0.0) %>
  <% end %>
</td>

app/views/shared/_to_main.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to image_tag("google.png", alt: "Google") + "To Gmail Contacts", user_omniauth_authorize_path(:google_oauth2), class: "btn", id:"logo" %>
  </div>  
  <div class="col-md-4">
    <%= link_to image_tag("facebook.png", alt: "Facebook") + "To Facebook Contacts", user_omniauth_authorize_path(:facebook), class: "btn", id:"logo" %>
  </div> 
  <div class="col-md-4">
    <%= link_to image_tag("email.png", alt: "Email") + "To Email Contacts", signin_path, class: "btn", id:"logo" %>
  </div>
</div>

app/views/shared/_top_loggedin.html.erb
<div class="row">
  <div class="profile-img">
    <%= link_to gravatar_for(current_user, size: 90), user_path(current_user) %>
  </div>
</div>
<div class="row">
  <div class="btn-group">
    <div class="btn", id:"logo"><%=current_user.name%></div>
    <div class="btn dropdown-toggle" data-toggle="dropdown", id:"logo"><i class="glyphicon glyphicon-chevron-down"></i></div>
    <ul class="dropdown-menu">
      <li><%= link_to "Address Book", users_path, class: "btn btn btn-link" %></li>
      <li><%= link_to "Message History", hotels_path, class: "btn btn btn-link" %></li>
      <li><%= link_to "Settings", edit_user_registration_path, class: "btn btn-link" %></li>
      <li><%= link_to "Sign/Out", destroy_user_session_path, method: "delete", class: "btn btn-link" %></li>
    </ul>
  </div>
</div>

app/views/shared/_top_main.html.erb
<div class="row">
  <div class="profile-img">
    <img src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=90" alt="">
  </div>
</div>

app/views/shared/_user_loggedin.html.erb
<tr>
  <td>
  <%= gravatar_for(user,size: 100)%>`
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= link_to "Track / Follow", user, class:"btn btn-primary"%>
  </td>
</tr>

app/views/shared/_user_main.html.erb
<tr>
  <td>
  <%= gravatar_for(user,size: 100)%>`
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= link_to "Track / Follow", user, class:"btn btn-info"%>
  </td>
</tr>

app/views/shared/_userfeed.html.erb
<% if @userfeed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/userfeed_item', collection: @userfeed_items %>
  </ol>
  <%= will_paginate @userfeed_items %>
<% end %>

app/views/shared/_userfeed_item.html.erb
<li id="<%= userfeed_item.id %>">
  <%= link_to gravatar_for(userfeed_item.user), userfeed_item.user %>
    <span class="user">
      <%= link_to userfeed_item.user.name, userfeed_item.user %>
    </span>
    <span class="content"><%= userfeed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(userfeed_item.created_at) %> ago.
    </span>
  <% if current_user == userfeed_item.user %>
    <%= link_to "delete", userfeed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: userfeed_item.content %>
  <% end %>
</li>