config/routes.rb
FirstApp::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do

    get 'signin',  to: 'devise/sessions#new'
    get 'signout', to: 'devise/sessions#destroy'
    get 'signup',  to: 'devise/registrations#new'
  end

  namespace :admin do
    resources :hotels, only: [:index, :edit, :update] do
      collection do
        post :import
      end
    end

    get 'database' => "database#index"

    root to: 'welcome#index'
  end

  resources :authentications
  resources :hotels do
    member do
      get :connecters
      post :upload

      get :send_user, action: 'send_user_form'
      put :send_user
    end
  end

  resources :microposts do
    member do
      get :send_msg, action: 'send_msg_form'
      put :send_msg
    end
  end  

  resources :users do
    member {get :following, :followers}
    member {get :connecting}
  end

  resources :prices do
    member {get :historical}
  end

  resources :permlinks, only: [:show]

  resources :relationships, only: [:create, :destroy]
  resources :prices, only: [:create, :destroy]
  resources :connections, only: [:create, :destroy]
 
  match '/staticcontact', to: 'static_pages#staticcontact'
  get '/cities/:city_code', to: 'static_pages#by_city'
  get '/countries/:country_code', to: 'static_pages#by_country'
  get '/companies/:company_code', to: 'static_pages#by_company'

  root to: 'static_pages#index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true

  default_scope order: 'microposts.created_at DESC'

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          :user_id => user.id)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    if params[:tofinal].index("@") == nil
      @user = User.find_by_name(params[:tofinal])

      if !@user
        redirect_to :back, alert: "Unable to locate user named \"#{params[:tofinal]}\""
      else
        redirect_to :back, notice: "Successfully sent a message to \"#{params[:tofinal]}\""
      end
    else
      arguments = {
        from: "noreply@thousandsoft.com",
        to: params[:tofinal],
        subject: "Message from #{current_user.name}: #{params[:subjectfinal]}",
        html:
        "<a href=http://www.thousandsoft.com><img src=http://placehold.it/200x400></img></a>
        <br>
        <a href=http://www.thousandsoft.com>The following message will go in the image: #{params[:messagefinal]}
        "
      }
      Mailgun().messages.send_email(arguments)
      redirect_to :back, notice: "Successfully send a message to \"#{params[:tofinal]}\""
    end

  end

  def destroy
    @micropost = current_user.microposts.where(:id => params[:id]).first
    if @micropost.present?
      @micropost.destroy
      flash[:success] = "Micropost deleted!"
    end
    # in both cases, redirect to root_path
    redirect_to :back
  end

  def send_msg_form
  end

  def send_msg
  end


end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user == micropost.user %>
    <%= link_to "Delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/microposts/_send_disappearing.html.erb
<%= form_for (@micropost) do |f| %>
  <%= hidden_field_tag :tofinal %>
  <%= hidden_field_tag :subjectfinal %>
  <%= hidden_field_tag :messagefinal %>
  <%= f.submit "Send Disappearing Message", onclick:'update();', class: 'btn btn-lg btn-info' %>
<% end %>
<script>
function update() {
  $('#tofinal').val($('#to').val());
  $('#subjectfinal').val($('#subject').val());
  $('#messagefinal').val($('#message').val());
}
</script>

app/views/microposts/_send_nondisappearing.html.erb
<%= form_for (@micropost) do |f| %>
  <%= hidden_field_tag :tofinal %>
  <%= hidden_field_tag :subjectfinal %>
  <%= hidden_field_tag :messagefinal %>
  <%= f.submit "Send Nondisappearing Message", onclick:'update();', class: 'btn btn-lg btn-info' %>
<% end %>
<script>
function update() {
  $('#tofinal').val($('#to').val());
  $('#subjectfinal').val($('#subject').val());
  $('#messagefinal').val($('#message').val());
}
</script>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/send_msg_form.js.erb
var form = "<%=j render 'microposts/forms/send_msg', micropost: @micropost %>";

$('body').append(form);

var modal = $('#micropost-send-msg-modal');

modal.modal();
modal.on('hidden.bs.modal', function () {
  modal.remove();
})

app/views/microposts/send_user_form.js.erb
var form = "<%=j render 'microposts/forms/send_user' %>";

$('body').append(form);

var modal = $('#micropost-send-user-modal');

modal.modal();
modal.on('hidden.bs.modal', function () {
  modal.remove();
})